import Image from "next/image";
import Link from "next/link";
import { ArrowUpRight } from "lucide-react";
import NewsletterForm from "@/components/ui/NewsletterForm";

// lucide-react dropped brand/logo icons; LinkedIn's glyph is drawn inline instead.
function LinkedinIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg viewBox="0 0 24 24" fill="currentColor" aria-hidden="true" {...props}>
      <path d="M20.45 20.45h-3.55v-5.57c0-1.33-.02-3.03-1.85-3.03-1.85 0-2.14 1.44-2.14 2.94v5.66H9.36V9h3.41v1.56h.05c.48-.9 1.64-1.85 3.37-1.85 3.6 0 4.27 2.37 4.27 5.45v6.29ZM5.34 7.43a2.06 2.06 0 1 1 0-4.12 2.06 2.06 0 0 1 0 4.12ZM3.56 20.45h3.56V9H3.56v11.45Z" />
    </svg>
  );
}

// CLAUDE.md §9 — footer nav omits "Home"; matches CONTENT.md's FOOTER section exactly.
const FOOTER_NAV = [
  { label: "About Us", href: "/about" },
  { label: "Our Solutions", href: "/solutions" },
  { label: "Our Team", href: "/team" },
  { label: "Newsroom", href: "/newsroom" },
  { label: "Careers", href: "/careers" },
  { label: "Contact", href: "/contact" },
];

const FOCUS_RING =
  "focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-liozio-gold focus-visible:ring-offset-2 focus-visible:ring-offset-liozio-charcoal";

export default function Footer() {
  return (
    <footer className="bg-liozio-charcoal text-white">
      <div className="mx-auto max-w-container px-gutter py-section lg:px-8 lg:py-section-lg">
        <div className="grid gap-10 sm:grid-cols-2 lg:grid-cols-4">
          <div className="sm:col-span-2 lg:col-span-2">
            <Image
              src="/images/The_LIOZIO_Solutions_Logo.png"
              alt="The LIOZIO Solutions"
              width={200}
              height={174}
              className="h-10 w-auto"
            />
            <p className="mt-4 font-heading text-sm font-semibold text-liozio-gold">
              Building What Africa Deserves.
            </p>

            {/* Query-based embed (?q=...&output=embed), not the pb=-parameter
                form — that parameter is an opaque, place-specific string
                normally generated by Google Maps' own "Share > Embed a map"
                UI, and isn't something safe to hand-reconstruct from memory;
                a wrong character risks a broken or mislocated embed. This
                query form is the well-documented, stable, no-API-key
                equivalent and geocodes "Ibadan, Oyo State, Nigeria" itself. */}
            <div className="mt-6 w-full overflow-hidden rounded-2xl lg:max-w-[280px]">
              <iframe
                src="https://www.google.com/maps?q=Ibadan,Oyo+State,Nigeria&output=embed"
                title="Map showing Ibadan, Nigeria — LIOZIO Solutions headquarters"
                loading="lazy"
                referrerPolicy="no-referrer-when-downgrade"
                className="h-36 w-full border-0 lg:h-40"
              />
            </div>
          </div>

          <nav aria-label="Footer">
            <h2 className="font-body text-sm font-medium text-white/60">
              Company
            </h2>
            <ul className="mt-4 space-y-3">
              {FOOTER_NAV.map((link) => (
                <li key={link.href}>
                  <Link
                    href={link.href}
                    className={`rounded-sm font-body text-sm text-white transition-colors hover:text-liozio-gold ${FOCUS_RING}`}
                  >
                    {link.label}
                  </Link>
                </li>
              ))}
            </ul>
          </nav>

          <div>
            <h2 className="font-body text-sm font-medium text-white/60">
              Our Solutions
            </h2>
            <ul className="mt-4 space-y-3">
              <li>
                <a
                  href="https://buyatdrumroll.com"
                  target="_blank"
                  rel="noopener noreferrer"
                  className={`inline-flex items-center gap-1 rounded-sm font-body text-sm text-white transition-colors hover:text-liozio-gold ${FOCUS_RING}`}
                >
                  Drumroll
                  <ArrowUpRight className="h-3.5 w-3.5" aria-hidden="true" />
                  <span className="sr-only">(opens in a new tab)</span>
                </a>
              </li>
            </ul>

            <h2 className="mt-8 font-body text-sm font-medium text-white/60">
              The LIOZIO Brief
            </h2>
            <div className="mt-4">
              <NewsletterForm compact />
            </div>
          </div>
        </div>

        <div className="mt-12 flex flex-col gap-6 border-t border-white/10 pt-8 sm:flex-row sm:items-center sm:justify-between">
          <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:gap-6">
            <ul className="flex gap-4 font-body text-xs text-white/70">
              <li>
                <Link href="/privacy" className={`rounded-sm hover:text-liozio-gold ${FOCUS_RING}`}>
                  Privacy Policy
                </Link>
              </li>
              <li>
                <Link href="/terms" className={`rounded-sm hover:text-liozio-gold ${FOCUS_RING}`}>
                  Terms of Use
                </Link>
              </li>
            </ul>
            <p className="font-body text-xs text-white/50">
              © 2026 The LIOZIO Solutions (RC: 7324519). All rights reserved.
            </p>
          </div>

          <div className="flex items-center gap-4">
            {/* LinkedIn confirmed per CLAUDE.md §9, but no URL was supplied in source — href is a TODO placeholder pending the real company page link. */}
            <a
              href="#"
              aria-label="The LIOZIO Solutions on LinkedIn (link to be confirmed)"
              className={`flex h-11 w-11 items-center justify-center rounded-full text-white/70 transition-colors hover:text-liozio-gold ${FOCUS_RING}`}
            >
              <LinkedinIcon className="h-5 w-5" aria-hidden="true" />
            </a>
            <span className="font-body text-xs text-white/50">
              A LIOZIO company.
            </span>
          </div>
        </div>
      </div>
    </footer>
  );
}
